# Generated by Django 2.0.7 on 2018-07-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20180726_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='logo',
        ),
    ]
