# Generated by Django 2.0.7 on 2018-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
