# Generated by Django 2.0.7 on 2018-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20180801_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoice',
            name='point',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='one_answer',
            name='point',
            field=models.CharField(max_length=4),
        ),
    ]
