# Generated by Django 2.0.7 on 2018-08-08 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0006_auto_20180801_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('score_question', models.IntegerField(default=0)),
                ('One_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.One_answer')),
                ('exam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to='exam.Exam')),
                ('multi_choice_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Multichoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
