# Generated by Django 2.0.7 on 2018-08-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score_question',
        ),
    ]
