# Generated by Django 2.0.7 on 2018-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_answer_score_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score_question',
            field=models.IntegerField(default=0),
        ),
    ]
