# Generated by Django 2.0.7 on 2018-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_answer_score_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoice',
            name='point',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='one_answer',
            name='point',
            field=models.IntegerField(max_length=4),
        ),
    ]
