# Generated by Django 2.0.7 on 2018-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20180814_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoice',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='one_answer',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
