# Generated by Django 2.0.7 on 2018-08-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20180824_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupst',
            name='assigned_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.Exam'),
        ),
    ]
