# Generated by Django 2.0.7 on 2018-08-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20180827_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_answer',
            name='is_rightANSWER',
            field=models.BooleanField(default=False),
        ),
    ]
