# Generated by Django 2.0.7 on 2018-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20180829_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoice',
            name='is_rightMULTI',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
