# Generated by Django 2.0.7 on 2018-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_exam_success_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
