# Generated by Django 2.0.7 on 2018-08-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_exam_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='one_answer',
            name='is_rightONE',
        ),
    ]
