# Generated by Django 2.0.7 on 2018-08-31 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0022_remove_one_answer_is_rightone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_passed',
        ),
        migrations.AddField(
            model_name='exam',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof', to=settings.AUTH_USER_MODEL),
        ),
    ]
