# Generated by Django 2.0.7 on 2018-07-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentification', '0003_auto_20180723_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_professor', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.RemoveField(
            model_name='free_text',
            name='question',
        ),
        migrations.RemoveField(
            model_name='multichoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='one_answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Free_Text',
        ),
        migrations.DeleteModel(
            name='Multichoice',
        ),
        migrations.DeleteModel(
            name='One_answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
